apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmt-monitor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tmt-monitor
  template:
    metadata:
      labels:
        app: tmt-monitor
    spec:
      containers:
      - name: tmt
        image: tmt-service:latest
        imagePullPolicy: Never
        env:
        - name: SUBWAY_LINE
          value: "L"
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi